Patient Age Group
StanfordBDHG/PediatricAppleWatchStudy pull request #52
Opened 2024-03-09 02:58 UTC by MatthewTurk247

# Patient Age Group

## :recycle: Current situation & Problem
We need a way to determine whether a patient is part of the upcoming pediatric study or the upcoming adult study so that UI can be updated accordingly.

## :gear: Release Notes 
- Adds the logic for tagging patients for pediatric/adult study based on date of birth and time of account creation. This information is stored in Firebase for later use in layout of the UI.

## :white_check_mark: Testing
Because of the `guard` statement at the beginning of the function body of interest, the bulk of the meaningful testing will be manual inspections of Firebase.

### Code of Conduct & Contributing Guidelines 

By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/StanfordBDHG/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordBDHG/.github/blob/main/CONTRIBUTING.md):
- [x] I agree to follow the [Code of Conduct](https://github.com/StanfordBDHG/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordBDHG/.github/blob/main/CONTRIBUTING.md).

2024-03-10 03:19 UTC, PSchmiedmayer requested changes
Thank you for the improvements @MatthewTurk247; I had feedback regarding the storage of the information. Apart from this the overall approach looks good to me.

2024-03-10 03:19 UTC, PSchmiedmayer commented on PAWS/PAWSStandard.swift
> +                _ = try await userBucketReference.child("ageGroup/isAdult").putDataAsync(ageGroupData)
I think you are putting the data in the Firebase cloud storage bucket and not Firebase Firestore live database. I would suggest to put the value in the user document in the Firestore.

2024-03-11 17:14 UTC, MatthewTurk247 commented on PAWS/PAWSStandard.swift
> +                _ = try await userBucketReference.child("ageGroup/isAdult").putDataAsync(ageGroupData)
So like this?
```swift
try await userDocumentReference.getDocument().setValue(age >= 18, forKey: "ageGroupIsAdult")
```

2024-03-13 18:13 UTC, PSchmiedmayer requested changes
@MatthewTurk247 Thank you for the updates. I have a question regarding the unit test. If we run into the code coverage issues I think we can merge it slightly below coverage as long as the core logic in e.g. a Date extension is tested.

2024-03-13 18:13 UTC, PSchmiedmayer commented on PAWSTests/PAWSTests.swift
I am not sure what behavior we are testing here; we should either put this in an extension of `Date` and test that extension. Otherwise we just test Swift Foundation functionality and we don't test anything in the app itself.

2024-03-15 16:27 UTC, MatthewTurk247 commented on PAWSTests/PAWSTests.swift
Gotcha, will do.

2024-03-21 22:51 UTC, PSchmiedmayer approved these changes

2024-03-21 22:51 UTC, merged